beepmein relative to now shortcut 'beepmein <minutes>' is now the only one that has precision in seconds

diff --git a/.experiments/bin/beepmein b/.experiments/bin/beepmein
--- a/.experiments/bin/beepmein
+++ b/.experiments/bin/beepmein
@@ -36,7 +36,8 @@ cat << EOF
         
         beepmein 22:10           # reminder ('at' time format)
                 
-        beepmein 3               # reminder (in 3 minutes, beepmein shortcut)
+        beepmein 3               # reminder (in 3 minutes, beepmein shortcut),
+                                 # also only input format that has precision in seconds.
                 
         beepmein 8:00 --alarm    # alarm (must be last parameter)
         
@@ -115,11 +116,6 @@ blink () {
     sleep "$2"
     xrandr --output "$monitor" --brightness "$now"
     done
-}
-
-# reminder sound 2, needs sox
-soxchord () {
-/usr/bin/play -n synth 2.5 sin 667 gain -5 bend .35,180,.25 .15,740,.53 0,-520,.3
 }
 
 # alarm failsafe (by misko), this will be used if 'alarmSample' is not found.
@@ -216,6 +212,9 @@ if [ "$1" != "--reaction" ] ; then
     # special case for minutes
     if [[ $attime == ?(-)+([0-9]) ]] ; then # is integer
         attime="now + $attime minutes"
+        # lets add delay in seconds, since 'at' is only about minutes,
+        # making this shortcut the only to seconds precise format.
+        delay="$(date +%_S)"
     fi
     
     # validate at time format, exit if fails
@@ -227,8 +226,10 @@ if [ "$1" != "--reaction" ] ; then
     fi
     [[ -z "$reason" ]] && reason="beep beep beep"
     echo "beepmein: $attime, reason: $reason $alarm"
+    
     # set 'at'
-    at "$attime" <<< "$(echo "DISPLAY=${DISPLAY} beepmein --reaction $alarm '${reason}'")" > /dev/null 2>&1 || { superecho "at input error." ; beep "2"; exit 1; } # beep two times for error
+    set -x
+    at "$attime" <<< "$(echo "sleep $delay; DISPLAY=${DISPLAY} beepmein --reaction $alarm '${reason}'")" > /dev/null 2>&1 || { superecho "at input error." ; beep "2"; exit 1; } # beep two times for error
     
 else
     # reaction
