mkay

diff --git a/.experiments/bin/epub2txtMany b/.experiments/bin/epub2txtMany
--- a/.experiments/bin/epub2txtMany
+++ b/.experiments/bin/epub2txtMany
@@ -11,15 +11,15 @@
 # tmp dir
 cleanup () {
   [ -n "$tmp" ] && rm -fr "$tmp"
-  killall feh
-  exit 0
 }
-tmp="/tmp/$RANDOM-$$-epub2txtMany"
-trap cleanup EXIT SIGTERM SIGINT 
-mkdir -m 700 "$tmp" || { echo '!! unable to create a tmp dir' >&2; tmp=; exit 1; }
+mktmp () {
+  tmp="/tmp/$RANDOM-$$-epub2txtMany"
+  trap cleanup EXIT SIGTERM SIGINT 
+  mkdir -m 700 "$tmp" || { echo '!! unable to create a tmp dir' >&2; tmp=; exit 1; }
+}
+mktmp
 # end tmp dir
 
-x="10" # for feh
 # main
 while [ $# -gt 0 ]; do
     file=$(readlink -f "$1")
@@ -31,14 +31,34 @@ while [ $# -gt 0 ]; do
     # convert to text
     epub2txt -a -n "$file" > "${dir}/${base}.txt" || exit 1
     # extract cover image
-    unzip "$file" "$(zipinfo -1 "$file" | grep -i cover | grep -E '\.jpg|\.jpeg|\.png' | tail -1)" -d "$tmp/" || { shift && continue; }
+    unzip -q "$file" -d "$tmp"
     pushd "$tmp" >/dev/null || exit
-    unset image # array
-    image="$(find "$tmp" -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) -print)"
-    #echo "echoing ${image[0]}" 
-    cp "${image[0]}" "${dir}/${base}.jpg" >/dev/null && { rm "${image[0]}" && catimg -H "${dir}/${base}.jpg"; } # due to tail, only one should survive
-    feh -x -g 450x700+$x+10 --scale-down "${dir}/${base}.jpg" &
-    x="$(( x + 50 ))" # feh x
+    # Find the content.opf file
+    OPF_FILE=$(find . -name "*.opf" | head -n 1)
+    # Check if the OPF file was found
+    if [ -z "$OPF_FILE" ]; then
+      echo "No content.opf file found."
+      exit 1
+    fi
+    # Extract cover image reference
+    COVER_ID=$(grep -i "cover" "$OPF_FILE" | grep -o 'content="[^"]*' | cut -d '"' -f2)
+    COVER_HREF=$(grep -i "$COVER_ID" "$OPF_FILE" | grep -o 'href="[^"]*' | cut -d '"' -f2)
+    # Check if the cover href was found
+    if [ -z "$COVER_HREF" ]; then
+      echo "No cover image reference found in the content.opf file."
+      exit 1
+    fi
+    # Find the cover image file
+    COVER_IMAGE=$(dirname "$OPF_FILE")/$COVER_HREF
+    # Check if the cover image file exists
+    if [ ! -f "$COVER_IMAGE" ]; then
+      echo "Cover image file not found."
+      exit 1
+    fi
+    # Copy the cover image to the current directory
+    cp "$COVER_IMAGE" "${dir}/${base}.jpg" >/dev/null && catimg -H "${dir}/${base}.jpg"
+    # clean the tmp dir of everything
+    cleanup && mktmp
     popd >/dev/null || exit
     #set +x
 
