validate string - file name

diff --git a/.experiments/bin/validate b/.experiments/bin/validate
--- a/.experiments/bin/validate
+++ b/.experiments/bin/validate
@@ -38,7 +38,7 @@ while [ $# -gt 0 ]; do
     errors="0"
     # a. always starts with NAP-
     if [[ $input != NAP-* ]]; then
-        echo "Začeti se mora na NAP-" 
+        >&2 echo "Začeti se mora na NAP-" 
         (( errors+=1 ))
     fi
 
@@ -47,7 +47,7 @@ while [ $# -gt 0 ]; do
     num="${#delimiter}" # Must be exactly four.
 
     if [[ $num != 4 ]]; then
-        echo "natančno štirje pomišljaji morajo biti in to brez presledkov." 
+        >&2 echo "Natančno štirje pomišljaji morajo biti in to brez presledkov." 
         (( errors+=1 ))
         raport
         shift
@@ -57,33 +57,37 @@ while [ $# -gt 0 ]; do
 
     fi
 
-    # c. already covered
+    # c. each part checked separatedly
 
     # d. title is UPPERCASE and basic ascii only
     # exactly 2nd member of array
     (( debug )) && echo "${array[1]}" # should be title
     if [[ ${array[1]} == *[![:ascii:]]* ]]; then
-    echo "Naslov mora biti izključno ascii"
-    (( errors+=1 ))
+        >&2 echo "Naslov mora biti izključno ascii"
+        (( errors+=1 ))
     fi
     if [[ ${array[1]} == *[[:lower:]]* ]]; then
-    echo "Naslov mora biti izključno z velikimi črkami"
-    (( errors+=1 ))
+        >&2 echo "Naslov mora biti izključno z velikimi črkami"
+        (( errors+=1 ))
+    fi
+    if [[ ${array[1]} != "$(echo "${array[1]}" | xargs)" ]]; then
+        >&2 echo "Presledki na začetku ali na koncu naslova"
+        (( errors+=1 ))
     fi
 
     # e. date is YYYYMMDD (Must be in the future, there could be a calc on how far away it is from current)
     (( debug )) && echo "${array[2]}" # should be date in YYYYMMDD format
     num2="${#array[2]}" # Must be exactly eight.
     if [[ $num2 != 8 ]]; then
-        echo "datum mora vsebovati natančno osem znakov YYYYMMDD" 
+        >&2 echo "Datum mora vsebovati natančno osem znakov YYYYMMDD" 
         (( errors+=1 ))
     fi
     if ! [[ ${array[2]} =~ ^[[:digit:]]+$ ]]; then
-        echo "datum mora biti zapisan numerično"
+        >&2 echo "Datum mora biti zapisan numerično"
         (( errors+=1 ))
     fi
     if ! date "+%Y%m%d" --date "${array[2]}" >/dev/null 2>&1; then
-        date "+%Y%m%d" --date "${array[2]}" 
+        date "+%Y%m%d" --date "${array[2]}" >&2
         (( errors+=1 ))
     fi
 
@@ -91,7 +95,7 @@ while [ $# -gt 0 ]; do
     dnevi=(081 082 083 084 085 086 087 090 060 050 090)
     if [[ ! "${dnevi[*]}" =~ ${array[3]} ]]; then
         # whatever you want to do when array doesn't contain value
-        echo "neveljaven dan ${array[3]}"
+        >&2 echo "Neveljaven dan ${array[3]}"
         (( errors+=1 ))
     fi
 
@@ -99,7 +103,7 @@ while [ $# -gt 0 ]; do
     version=(F1 F2 F3 F4 F5 F6 F7 F8 F9 CF)
     if [[ ! "${version[*]}" =~ ${array[4]} ]]; then
         # whatever you want to do when array doesn't contain value
-        echo "neveljavna verzija ${array[4]}"
+        >&2 echo "Neveljavna verzija ${array[4]}"
         (( errors+=1 ))
     fi
 
@@ -111,6 +115,6 @@ done
 
 # global = errors for all files
 if (( globalerrors != 0 )); then
-    echo "Napak = $globalerrors"
+    >&2 echo "Napak = $globalerrors"
     exit 1
 fi
